### PR TITLE
Distinguish between errors and warnings

### PR DESCRIPTION
**Pull request by jerryxgh**
Change-Id: I483282ca2f052eba401f74e494f2eee2bcfd9b9f

### CODE REVIEW

**Comment by erickgnavar** [comment]
Hi, thanks for the contribution, can you specify where in the documentation of `sqlfluff` is defined that `PRS` es a code for all kind of errors? I was checking but I only found [this](https://docs.sqlfluff.com/en/stable/rules.html#inline-ignoring-errors) which explains that they are parsing errors and not general errors

**Comment by jerryxgh** [comment]
Thank you for your time, and `flymake-sqlfluff` is very userful for me, great! Actually I've found no document about sqlfluff general error definition. I choose code of `PRS` items as `error`, but other as `warning` has two reasons:

1. `flymake-sqlfluff` count all sqlfluff output items as errors, that makes me feel more stressed, but most of them just style problems
2. I found `PRS` items is highlight by sqlfluff command output, and they are more important indeed
image

I found more error definition in this source file:[error](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/errors.py), like 'PRS', 'LXR', 'TMP', maybe we should take all the three as errors?

**Comment by jerryxgh** [comment]
And I have add some optimization to improve experience when edit big sql file.

**Comment by erickgnavar** [comment]
> Thank you for your time, and `flymake-sqlfluff` is very userful for me, great! Actually I've found no document about sqlfluff general error definition. I choose code of `PRS` items as `error`, but other as `warning` has two reasons:
> 
> 1. `flymake-sqlfluff` count all sqlfluff output items as errors, that makes me feel more stressed, but most of them just style problems
> 2. I found `PRS` items is highlight by sqlfluff command output, and they are more important indeed
>    image
> 
> I found more error definition in this source file:[error](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/errors.py), like `PRS`, `LXR`, `TMP`, maybe we should take all the three as errors?
> 
> And I add code as prefix of error description, that will maybe more convenient for searching and troubleshooting?

Sound good, by now we can only have `PRS` as errors and in the future maybe we can allow the user to customizes what codes prefix are errors or warnings

**Comment by erickgnavar** [comment]
> And I have added some optimization to improve experience when edit big sql file.

This looks great, I have to make some tests,  but can we handle this in a another PR?

**Comment by jerryxgh** [comment]
No problem, next what should I do, does it need me to withdraw the commint?

> > And I have added some optimization to improve experience when edit big sql file.
> 
> This looks great, I have to make some tests, but can we handle this in a another PR?

**Pull request merged**
